# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_of_level',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
