# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='id',
        ),
        migrations.AddField(
            model_name='level',
            name='level_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
