# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_auto_20180105_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_title',
            field=models.CharField(default='JNDARC', max_length=30),
            preserve_default=False,
        ),
    ]
