# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_level_level_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='answer1',
            field=models.CharField(default='john', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='answer2',
            field=models.CharField(default='john', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='answer3',
            field=models.CharField(default='john', max_length=20),
            preserve_default=False,
        ),
    ]
