# Generated by Django 2.0.2 on 2018-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0011_auto_20180917_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time_of_submission',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
