# Generated by Django 2.0.2 on 2018-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0015_auto_20180920_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_of_level',
            field=models.DateTimeField(),
        ),
    ]
