# Generated by Django 2.0.2 on 2018-09-21 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0016_auto_20180921_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_of_level',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 22, 4, 8, 630398)),
        ),
    ]
