# Generated by Django 2.2.5 on 2019-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0018_auto_20180921_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvariable',
            name='success_sign_up',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_answer',
            field=models.CharField(max_length=500),
        ),
    ]
